default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: our-memories-development

test:
  <<: *default
  database: our-memories-test

production:
  <<: *default
  database: our-memories-production
  url: <%= ENV['DATABASE_URL'] %>
